server:
  port: 8088


##数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_sys?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root123
  #模板引擎配置
  thymeleaf:
    encoding: UTF-8
    #suffix: .html  默认后缀
    #prefix: classpath:/templates/  默认前缀

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  typeAliasesPackage: com.lzw.order_admin_sys.entity

logging:
  config: classpath:logback-spring.xml
  level:
    com.lzw.admin.mapper: debug

